<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\Enums\WokLevel2.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ClassDiagram1.cd" />
  </ItemGroup>

</Project>
