/* Lógico_1: */

CREATE TABLE DEPARTAMENTO (
    Num_Dep DECIMAL PRIMARY KEY,
    Nome VARCHAR,
    CPF_Gerente DECIMAL
);

CREATE TABLE PROJETO (
    Local VARCHAR,
    Num_Proj INTEGER PRIMARY KEY,
    Nome VARCHAR,
    Num_Dep_FK INTEGER
);

CREATE TABLE FUNCIONARIO (
    CPF DECIMAL PRIMARY KEY,
    Nome VARCHAR,
    Salario DECIMAL,
    Sexo VARCHAR,
    Endereco VARCHAR,
    DataNascimento DATE,
    FK_FUNCIONARIO_CPF DECIMAL,
    FK_DEPARTAMENTO_Num_Dep DECIMAL,
    DataInicio DATE
);

CREATE TABLE DEPENDENTE (
    Nome VARCHAR PRIMARY KEY,
    Sexo VARCHAR,
    DataNascimento DATE,
    Parentesco VARCHAR,
    CPF_Funcionario_FK DECIMAL
);

CREATE TABLE TRABALHA_EM (
    FK_PROJETO_Num_Proj INTEGER,
    FK_FUNCIONARIO_CPF DECIMAL,
    Horas FLOAT
);

CREATE TABLE LOCAIS (
    Nome_Local VARCHAR,
    Num_Dep_FK INTEGER
);
 
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_2
    FOREIGN KEY (CPF_Gerente)
    REFERENCES FUNCIONARIO (CPF)
    ON DELETE CASCADE;
 
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_3
    FOREIGN KEY (FK_PROJETO_Num_Proj)
    REFERENCES PROJETO (Num_Proj)
    ON DELETE CASCADE;
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_2
    FOREIGN KEY (FK_FUNCIONARIO_CPF)
    REFERENCES FUNCIONARIO (CPF);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_3
    FOREIGN KEY (FK_DEPARTAMENTO_Num_Dep)
    REFERENCES DEPARTAMENTO (Num_Dep)
    ON DELETE CASCADE;
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_4
    FOREIGN KEY (FK_DEPENDENTE_Nome)
    REFERENCES DEPENDENTE (Nome)
    ON DELETE CASCADE;
 
ALTER TABLE TRABALHA_EM ADD CONSTRAINT FK_TRABALHA_EM_1
    FOREIGN KEY (FK_PROJETO_Num_Proj)
    REFERENCES PROJETO (Num_Proj)
    ON DELETE SET NULL;
 
ALTER TABLE TRABALHA_EM ADD CONSTRAINT FK_TRABALHA_EM_2
    FOREIGN KEY (FK_FUNCIONARIO_CPF)
    REFERENCES FUNCIONARIO (CPF)
    ON DELETE SET NULL;/* Modelo Lógico Final Corrigido */

CREATE TABLE DEPARTAMENTO (
    Num_Dep DECIMAL PRIMARY KEY,
    Nome VARCHAR(100),
    CPF_Gerente DECIMAL
);

CREATE TABLE PROJETO (
    Local VARCHAR(100),
    Num_Proj INTEGER PRIMARY KEY,
    Nome VARCHAR(100),
    Num_Dep_FK DECIMAL -- Chave para o Departamento
);

CREATE TABLE FUNCIONARIO (
    CPF DECIMAL PRIMARY KEY,
    Nome VARCHAR(100),
    Salario DECIMAL(10,2),
    Sexo VARCHAR(1),
    Endereco VARCHAR(200),
    DataNascimento DATE,
    FK_FUNCIONARIO_CPF DECIMAL, -- Supervisor
    FK_DEPARTAMENTO_Num_Dep DECIMAL, -- Lotação
    DataInicio DATE
);

CREATE TABLE DEPENDENTE (
    Nome VARCHAR(100) PRIMARY KEY,
    Sexo VARCHAR(1),
    DataNascimento DATE,
    Parentesco VARCHAR(50),
    CPF_Funcionario_FK DECIMAL -- Chave para o Pai/Mãe
);

CREATE TABLE TRABALHA_EM (
    FK_PROJETO_Num_Proj INTEGER,
    FK_FUNCIONARIO_CPF DECIMAL,
    Horas FLOAT
);

CREATE TABLE LOCAIS (
    Nome_Local VARCHAR(100),
    Num_Dep_FK DECIMAL -- Chave para o Departamento
);

/* --- DEFINIÇÃO DAS RELAÇÕES (FOREIGN KEYS) --- */

-- Gerência do Departamento
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_GERENTE
    FOREIGN KEY (CPF_Gerente) REFERENCES FUNCIONARIO (CPF);

-- Supervisão (Auto-relacionamento)
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_SUPERVISOR
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO (CPF);

-- Lotação (Onde o funcionário trabalha)
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_LOTACAO
    FOREIGN KEY (FK_DEPARTAMENTO_Num_Dep) REFERENCES DEPARTAMENTO (Num_Dep);

-- Projeto pertence a um Departamento
ALTER TABLE PROJETO ADD CONSTRAINT FK_PROJETO_DEP
    FOREIGN KEY (Num_Dep_FK) REFERENCES DEPARTAMENTO (Num_Dep);

-- Dependente ligado ao Funcionário
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_FUNC
    FOREIGN KEY (CPF_Funcionario_FK) REFERENCES FUNCIONARIO (CPF);

-- Local ligado ao Departamento
ALTER TABLE LOCAIS ADD CONSTRAINT FK_LOCAIS_DEP
    FOREIGN KEY (Num_Dep_FK) REFERENCES DEPARTAMENTO (Num_Dep);

-- Relacionamento N:N (Trabalha_Em)
ALTER TABLE TRABALHA_EM ADD CONSTRAINT FK_TRABALHA_PROJ
    FOREIGN KEY (FK_PROJETO_Num_Proj) REFERENCES PROJETO (Num_Proj);

ALTER TABLE TRABALHA_EM ADD CONSTRAINT FK_TRABALHA_FUNC
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO (CPF);